users/forms.py
import wtforms
from wtforms import validators
from wtforms.validators import DataRequired
from app.models import Post 

class PostForm(wtforms.Form):
      body = wtforms.TextAreaField("", validators=[validators.DataRequired()]);

users/blueprint.py
import os;

from flask import g;
from flask_login import login_required
from flask import Blueprint, flash, redirect, render_template, request;
from flask import url_for;

from app.models import User, Post;
from app import app, db;
from users.forms import PostForm
users = Blueprint('users', __name__, template_folder='templates')

@users.route('/to_friend/<int:id>')
@login_required
def add_to_friends(id):
      user = User.query.get_or_404(id);
      if not user or g.user == user:
            return redirect('index.html');
      
      
      g.user.friends.append(user);
      
      db.session.add(g.user);
      db.session.commit();
      flash(" {0} added to friend list".format(user.name), "success")
      return redirect( url_for('users.profile', id = g.user.id));

@users.route('/<int:id>', methods=['GET', 'POST'])
def profile(id):
      user = User.query.get_or_404(id);
      if not user:
            return redirect('index.html');
      if g.user == user:
            if request.method == 'POST':
                  form = PostForm(request.form);
                  if form.validate():
                        post = Post();
                        form.populate_obj(post);
                        post.user = user;
                        db.session.add(post);
                        db.session.commit();
                        return redirect(url_for('users.profile', id=id));
            else:
                  return render_template("users/profile.html",
                                                user = user,
                                                form = PostForm()
                                          );
      return render_template('users/profile.html', user = user);

users/templates/users/profile.html
{% extends "base.html" %}

{% from "macros/form_field.html" import form_field %}

{% block title %} {{user.name}} {% endblock %}

{% block extra_styles %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/myStyle.css') }}">
{% endblock %}

{% block profile  %}
<div id="user-photo">
      <img src="{{user.photo}}" alt="" width="250" height="250"> 
</div>
      {% if g.user == user %}
      <div id="change-avatar">
                   <a href="{{ url_for('upload_avatar', id = user.id) }}"  class="btn btn-default btn-xs dropdown-toggle">Change avatar</a>
      </div>   
      {% endif %}
      <h3>{{user.name}}</h3>
      <h6> <a href= "mailto:{{user.email}}"> {{user.email}} </a> </h6>
      <hr>

      {% if user != g.user and g.user.is_authenticated %}
            {% if g.user not in user.friends %}
                  <a href="{{url_for('users.add_to_friends', id = user.id) }}" class="btn btn-default btn-xs dropdown-toggle">
                        Add to friends
                  </a>
            {% else %}
                  <div class="btn btn-success btn-xs dropdown-toggle">
                        Your friend
                  </div>
            {% endif %}
      {% endif %}



      {% if form %}
            <h4>What's new</h4>
            <form action=""  class = "form form-horizontal"   method="POST">
                  {% for field in form %}
                              <div class="form-group{% if field.errors %} has-error has-feedback{% endif %}">
                                    <div class="col-sm-12">
                                          {{ field(class='form-control') }}

                                          {% if field.description %}
                                                <span class="help-block">
                                                      {{field.description|safe}}
                                                </span>
                                          {% endif %}
                                          {% for error in field.errors %} 
                                                <span class="help-block">{{error }}</span>
                                          {% endfor %} 
                                    </div>
                              </div>
                  {% endfor %}

            <div class="form-group" id="create-post-button">
                        <div class="col-sm-offset-3 col-sm-9">
                              <button type="submit" class="btn btn-default">Create</button>
                        </div>
            </div>

            </form>
      <hr>
      {% endif %}

 



{% endblock %}

{% block content %}
      <div class="row ">
            <div class="col-md-7 thumbnail ">
                  <h4 class="top-profile-element ">{{user.name}}'s wall:</h4>
                  {% for post in user.posts %}
                  <p>
                        <div id="myPost">
                              {{post.body}}
                              <div id="myTime"> {{post.created_timestamp.strftime("%Y-%m-%d %H:%M")}} </div>
                        </div>
                  </p>          
                  {% endfor %}
            </div>


            <div class="col-md-5">
                  <div class="row">
                        <div class="col-md-12 thumbnail group-container">
                        {% if user.friends.count() != 0 %}
                              <h4 class="top-profile-element">Friends:</h4>
                             {%for friend in user.friends  %}
                                    <div class="media">
                                          <a href="{{url_for('users.profile', id = friend.id) }}">
                                          <div class="media-left media-middle">
                                                
                                                      <img class="media-object" src="{{friend.photo}}" width="32" height="32">
                                                
                                          </div>
                                          <div class="media-body media-middle">
                                                <h5 class="media-heading"> {{friend.name}}</h5>
                                          
                                          </div>
                                          </a>
                                    </div>
                               {% endfor %}
                        {% endif %}
                        </div>
        
                        <div class="col-md-12 thumbnail group-container">
                              {% if user.followers.count() != 0 %}
                                    <h4 >Followers:</h4>
                                          {%for follower in user.followers  %}

                                                <div class="media">
                                                      <a href="{{url_for('users.profile', id = follower.id) }}">
                                                      <div class="media-left media-middle">
                                                                  <img class="media-object" src="{{follower.photo}}" width="32" height="32">
                                                      </div>
                                                      <div class="media-body media-middle">
                                                            <h5 class="media-heading"> {{follower.name}}</h5>
                                                                  {% if follower not in user.friends %}

                                                                  {% if g.user == user  %}
                                                                        <a href="{{ url_for('users.add_to_friends', id = follower.id) }}" class="btn btn-default btn-xs dropdown-toggle " >
                                                                        <h8> [Add to friends] </h8>
                                                                        </a>
                                                                  {% endif %}
                                                            {% endif %}
                                                      </div>
                                                      </a>
                                                </div>
                                    {% endfor %}
                              {% endif %}
                        </div>
                  </div>


            </div>

      </div>

{% endblock %}